### ISSUE TITLE
bad hardwired path

### ISSUE THREAD

**Issue by utke1** [FlorentBuissonOReilly/BehavioralDataAnalysis#1]
https://github.com/FlorentBuissonOReilly/BehavioralDataAnalysis/blob/a18dea2122d4e54bd692093df12a493ddc663f33/Chapter%202%20-%20Behaviors%2C%20Causality%20and%20Prediction/chap%202%20-%20generating%20data.R#L12

**Comment by FlorentBuissonOReilly** [comment]
Resolved for when the R scripts are open in Rstudio, I will revisit the issue when creating the R notebooks.
