### ISSUE TITLE
where do I get H1.csv ? 

### ISSUE THREAD

**Issue by utke1** [FlorentBuissonOReilly/BehavioralDataAnalysis#3]
https://github.com/FlorentBuissonOReilly/BehavioralDataAnalysis/blob/a18dea2122d4e54bd692093df12a493ddc663f33/Chapter%203%20-%20Building%20Causal%20Diagrams%20From%20Scratch/chap%203%20-%20loading%20and%20prepping%20example%20data.R#L13

**Comment by FlorentBuissonOReilly** [comment]
I added the file.
