### ISSUE TITLE
hardwired absolute path

### ISSUE THREAD

**Issue by utke1** [FlorentBuissonOReilly/BehavioralDataAnalysis#8]
https://github.com/FlorentBuissonOReilly/BehavioralDataAnalysis/blob/775d1872630f2ec8f92758236729499a831e916b/Chapter%208%20-%20Experimental%20design%202%20-%20stratified%20randomization/chap%208%20-%20generating%20data.R#L7

**Comment by FlorentBuissonOReilly** [comment]
Resolved.
